### ISSUE TITLE
Error on custom assertions on libraries

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#31]
Hi, I'm checking how to write custom assertions, this is a great package, I'm including this in my production codes.

Here is a custom assertion, it checks if the variable is a sfnetworks object:

```R
typed_sfnetworks <- typed::as_assertion_factory(function(value) {
    if (!sfnetworks::is.sfnetwork(value)){
        e <- sprintf(
        "%s\n%s",
        "type mismatch",
        waldo::compare(
            typeof(value),
            "sfnetworks",
            x_arg = "typeof(value)",
            y_arg = "expected"))
        stop(e, call. = FALSE)
    }
    value
})
```

Now trying to use it:

```R
> typed_sfnetworks() ? x
Error in process_assertion_factory_dots(...) : 
  can not found the function "process_assertion_factory_dots"
```

What would be the way to create this assertion?

Thx!

**Comment by moodymudskipper** [comment]
Hi @latot. Thanks for your report, your issue would be solved if you used `library(typed)`

```
library(typed)
typed_sfnetworks() ? x
```

There are 2 issues in your code, one is mine and one is yours. Yours is that you're using `?` without attaching the package so you're using the base `?`, this can't work, you could define the following sort it out if there were no other issue in my code: 

```
`?` <- typed::`?`
```

The other issue is mine, it's a NSE issue, `process_assertion_factory_dots` is not searched at the right place, the following works as a workaround until I push a fix:

```
process_assertion_factory_dots <- typed::process_assertion_factory_dots
`?` <- typed::`?`
declare <- typed::declare
typed_sfnetworks() ? x
```

you can 

for two reasons one good and one bad:

* The "bad" reason is that there seems to be an issue with `process_assertion_factory_dots` being evaled in an incorrect environment, I'll solve this when I get the chance
* The "good" reason is that the `?` you use here, if you don't attach the typed package, is from base, so it can't have the intended effect.

To get around these  issues you can define locally :

```
process_assertion_factory_dots <- typed::process_assertion_factory_dots
`?` <- typed::`?`
declare <- typed::declare
typed_sfnetworks() ? x
```

A more economic workaround would be to use `declare()` rather than `?` but we still need to hack around `process_assertion_factory_dots`

```
process_assertion_factory_dots <- typed::process_assertion_factory_dots
typed::declare("x", typed_sfnetworks())
typed_sfnetworks() ? x
```

**Comment by moodymudskipper** [comment]
Additionally, maybe you don't need to build a custom assertion factory here, you can inherit from `Any()` and restrict the type :

```
typed_sfnetwork <- typed::Any(... = "type mismatch" ~ sfnetworks::is.sfnetwork(value))
# or just  typed::Any(is.sfnetwork = TRUE) if sfnetworks is attached or imported
typed::declare("x", typed_sfnetwork) # Without (), Not typed_sfnetwork() !
```

**Comment by latot** [comment]
Hi!

Well, is not ideal to use ```library``` inside a package.

I did something similar in the end:

```
## manual namespace: end
## typed vars
#' @importFrom typed ?
#' @importFrom typed check_arg
#' @importFrom typed check_output
#' @importFrom typed declare
#' @importFrom typed process_assertion_factory_dots
## manual namespace: end
```

That works, after using it then run ```devtools::document``` and the export will be completed, still is not ideal to do that, no idea if is possible to use ```::``` inside a package? like instead use ```check_arg``` use ```typed::check_arg```, maybe will do the trick? no idea.


> Additionally, maybe you don't need to build a custom assertion factory here, you can inherit from `Any()` and restrict the type :
> 
> ```
> typed_sfnetwork <- typed::Any(... = "type mismatch" ~ sfnetworks::is.sfnetwork(value))
> # or just  typed::Any(is.sfnetwork = TRUE) if sfnetworks is attached or imported
> typed::declare("x", typed_sfnetwork) # Without (), Not typed_sfnetwork() !
> ```

:O how works that line? I try reading the code of ```Any``` still I don't get how works that line using ```type mismatch```

I still found this lib incredible, in some days, I'll finish using it in a production lib, what I think would be great, is get better documentation, improve that and will be a lot easier to use!

Thx!

**Comment by moodymudskipper** [comment]
> That works, after using it then run `devtools::document` and the export will be completed, still is not ideal to do that, no idea if is possible to use `::` inside a package? like instead use `check_arg` use `typed::check_arg`, maybe will do the trick? no idea.

IIRC you get a warning if you use `yourownpackage::` on your own package's code, but I'll find a way to make it work.

> :O how works that line? I try reading the code of `Any` still I don't get how works that line using `type mismatch`

The code of this package is quite complex, and the syntax I use here is just weird, I regret it a bit, but I used `... =` because I wanted to keep the length arg first so we can use it by position, you can also do `typed::Any(,"type mismatch" ~ sfnetworks::is.sfnetwork(value))` with the coma after the bracket. 

> I still found this lib incredible, in some days, I'll finish using it in a production lib, what I think would be great, is get better documentation, improve that and will be a lot easier to use!

Thanks so much, I'll fix a few things (this and your other tickets) and release a new version when I get the chance to spend a little time on this project.

**Comment by moodymudskipper** [comment]
Follow up in #48 and #49
