### ISSUE TITLE
Return fails when using local inside a function with typed

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#40]
Hi all!, this was pretty unexpected, here the reduced example:

```R
f <- typed::Integer() ? function() {

  ret <- local({
    return(1.0)
  })

  as.integer(10)
}
f()
Error: In `eval(quote({     return(check_output(1, typed::Integer())) }), new.env())` at `check_output(1, typed::Integer())`:
wrong return value, type mismatch
`typeof(value)`: "double" 
`expected`:      "integer"
```

What happens, seems for some reason, then using typed, the return inside local finish the whole function with the return value instead only finish the local block.

This bug is pretty important because will cause to return the wrong values on any function the uses local + return.

As you wrote before, there is a clean step of return values, I don't know if that step is that helpful, because is too hard to think in every possibility of how ppl will use return, and they are not easy to debug, there can exists even more functions and libs that uses return and envs.

Thx!

**Comment by moodymudskipper** [comment]
I solved the case when wrapping in `function()`, I can easily add the fix for `local()` as well, but that's a rabbit hole, because then I must add all NSE functions and there will be cases I can't handle like below:

```
some_quoting_function <- function(arg) substitute(arg)
f <- typed::Integer() ? function() {

  some_quoting_function(return(1.0))

  as.integer(10)
}
```

I think another approach might make more sense, detect only return calls that are either at the top level or nested into control flow construct calls only (if, for, while, repeat), + `{`. This will solve this case and still work with #36 .

**Comment by latot** [comment]
:O Thx!, I would recommend, this issues, add tests for the lib, can help on the future :)

**Comment by moodymudskipper** [comment]
Can you try again, I've pushed some changes ?

**Comment by latot** [comment]
Yay! is working!
